// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/font-preview/Current.tsx": () => import("../components/mockups/font-preview/Current.tsx"),
  "./components/mockups/font-preview/KGCorner.tsx": () => import("../components/mockups/font-preview/KGCorner.tsx")
};
